# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 55cbdb50f3c69b2da068f0fff29d493acd024149fdc514cd539bc3b07bef6d44e2b70947c46cd0a01a840699b24910afb7faa6cced189ede8bdcb947ed40663e

test:
  secret_key_base: 700d14ab0c1c6b940f7378b61822ed21402f4c0370c47d2cc27b2e7dfe142bee6e2a8190f44c12dc9d8a40f78c6778014023f0e8dc70b26d141e676506b98d50

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
